// Copyright 2025 IMAN SHIRANI
// Licensed under the Apache 2.0 License
// https://github.com/ADN-DevTech/3dsMax-OSL-Shaders/blob/master/LICENSE.txt


// SDF_Displace.osl by IMAN SHIRANI
// 2025-09-11


shader SDF_Displace
[[
        string category = "SDF\\Modifiers",
    string logo     = "SDF.png"
]]
(
    
    float SDF_In = 0.0,
    
    
    float Noise_In = 0.0,
    
    
    float Amount = 0.1,

    output float SDF_Out = 0.0
)
{
    
    SDF_Out = SDF_In + (Noise_In * Amount);
}