// Copyright 2025 IMAN SHIRANI
// Licensed under the Apache 2.0 License
// https://github.com/ADN-DevTech/3dsMax-OSL-Shaders/blob/master/LICENSE.txt



// SDF_Shell.osl by IMAN SHIRANI
// 2025-09-11


shader SDF_Shell
[[
        string category = "SDF\\Modifiers",
    string logo     = "SDF.png"
]]
(
    
    float SDF_In = 0.0,
    
    
    float Thickness = 0.1,

    output float SDF_Out = 0.0
)
{
    
    float abs_sdf = abs(SDF_In);
    
    
    SDF_Out = abs_sdf - (Thickness / 2.0);
}