// Copyright 2025 IMAN SHIRANI
// Licensed under the Apache 2.0 License
// https://github.com/ADN-DevTech/3dsMax-OSL-Shaders/blob/master/LICENSE.txt

// SDF_Round.osl by IMAN SHIRANI
// 2025-11-25



shader SDF_Round
[[
        string category = "SDF\\Modifiers",
    string logo     = "SDF.png"
]]

(
   
    float InputSDF = 0.0,
    
    
    float Radius = 0.1 [[ string label = "Round Radius", float min = 0.0 ]],
    
    output float SDF_Out = 0.0
)
{
    
    SDF_Out = InputSDF - Radius;
}