// Copyright 2025 IMAN SHIRANI
// Licensed under the Apache 2.0 License
// https://github.com/ADN-DevTech/3dsMax-OSL-Shaders/blob/master/LICENSE.txt


// SDF_Transform.osl by IMAN SHIRANI
// 2025-09-11


shader SDF_Transform
[[
    string logo     = "SDF.png"
]]
(
    point Position_In = P,
    vector Amount = vector(0.0), 

    output point Position_Out = P
)
{
    
    Position_Out = Position_In - Amount;
}