// Copyright 2025 IMAN SHIRANI
// Licensed under the Apache 2.0 License
// https://github.com/ADN-DevTech/3dsMax-OSL-Shaders/blob/master/LICENSE.txt

// SDF_Rotate.osl by IMAN SHIRANI
// 2025-09-11

void rotate_x(output point p, float angle) {
    float rad = radians(angle);
    float s = 0.0;
    float c = 0.0;
    sincos(rad, s, c);
    p = point(p[0], p[1]*c - p[2]*s, p[1]*s + p[2]*c);
}

void rotate_y(output point p, float angle) {
    float rad = radians(angle);
    float s = 0.0;
    float c = 0.0;
    sincos(rad, s, c);
    p = point(p[0]*c + p[2]*s, p[1], -p[0]*s + p[2]*c);
}

void rotate_z(output point p, float angle) {
    float rad = radians(angle);
    float s = 0.0;
    float c = 0.0;
    sincos(rad, s, c);
    p = point(p[0]*c - p[1]*s, p[0]*s + p[1]*c, p[2]);
}

shader SDF_Rotate
[[
    string category = "SDF\\Domain",
    string logo     = "SDF.png"
]]
(
    point Position_In = P,
    float Angle_X = 0.0,
    float Angle_Y = 0.0,
    float Angle_Z = 0.0,

    output point Position_Out = P
)
{
    Position_Out = Position_In;
    rotate_z(Position_Out, Angle_Z);
    rotate_y(Position_Out, Angle_Y);
    rotate_x(Position_Out, Angle_X);
}