
// SDF_Array_2D.osl by IMAN SHIRANI
// 2025-09-11



shader SDF_Array_2D
[[
    string logo     = "SDF.png"
]]
(
    point Position_In = P,

    
    int Count_X = 5,
    int Count_Y = 3,

   
    float Spacing_X = 2.0,
    float Spacing_Y = 2.0,

    
    output point Position_Out = P,
    output point Cell_ID = point(0.0) 
)
{
    
    vector count = vector(Count_X, Count_Y, 1.0);
    vector spacing = vector(Spacing_X, Spacing_Y, 1.0);
    
    
    Cell_ID = floor(Position_In / spacing + 0.5);

    
    if (abs(Cell_ID[0]) * 2.0 >= count[0] || abs(Cell_ID[1]) * 2.0 >= count[1]) {
        
        Position_Out = point(1e20); // A very large number
    } else {
        
        Position_Out = mod(Position_In + 0.5 * spacing, spacing) - 0.5 * spacing;
    }
    
    Position_Out[2] = Position_In[2];
}