// Copyright 2025 IMAN SHIRANI
// Licensed under the Apache 2.0 License
// https://github.com/ADN-DevTech/3dsMax-OSL-Shaders/blob/master/LICENSE.txt



// SDF_Scale.osl by IMAN SHIRANI
// 2025-09-11


shader SDF_Scale
[[
    string logo     = "SDF.png"
]]

(
    point Position_In = P,
    float Scale = 1.0,

    output point Position_Out = P,
    output float Scale_Out = 1.0
)
{
    
    Position_Out = Position_In / Scale;
    Scale_Out = Scale; 
}