// Copyright 2025 IMAN SHIRANI
// Licensed under the Apache 2.0 License
// https://github.com/ADN-DevTech/3dsMax-OSL-Shaders/blob/master/LICENSE.txt

// SDF_ImageToSDF.osl by IMAN SHIRANI
// 2025-11-25
float get_val_safe(string file, float u_c, float v_c, int chan, int inv, float gn) {
    if (file == "") return 0.0;
    
    
    color c = texture(file, u_c, v_c, "wrap", "periodic", "interp", "bicubic");
    float v = 0.0;
    
    
    if (chan == 0) v = (c[0]+c[1]+c[2])/3.0; 
    else if (chan == 1) v = c[0]; 
    else if (chan == 2) v = c[1]; 
    else if (chan == 3) v = c[2]; 
    else v = luminance(c); 
    

    if (inv) v = 1.0 - v;
    
    return pow(max(0.0, v), gn);
}

shader ImageToSDF_Pro
[[
    string logo     = "SDF.png"
]]

(
	
    string TextureFile = "" [[ string widget = "filename" ]], 
    int Channel = 4 [[ string widget = "mapper", string options = "RGB:0|Red:1|Green:2|Blue:3|Luminance:4" ]],
    
    float Gain = 1.0 [[ string label = "Contrast" ]],
    float SurfaceLevel = 0.5 [[ string label = "Cutoff Threshold" ]],
    float Amplitude = 1.0 [[ string label = "Extrude Height" ]],
    float Smoothness = 0.00 [[ string label = "Blur / Softness" ]],
    
    int InvertColor = 0 [[ string widget = "checkbox", string label = "Invert Colors (Negative)" ]],
    int FlipU = 0 [[ string widget = "checkbox", string label = "Flip Horizontal (Mirror)" ]],
    int FlipV = 1 [[ string widget = "checkbox", string label = "Flip Vertical (Upside Down)" ]], 
    
    point UV = point(u, v, 0),
    output float outSDF = 0.0
)
{
    if (TextureFile == "") { outSDF = 1.0; return; }

  
    float final_u = FlipU ? (1.0 - UV[0]) : UV[0];
    float final_v = FlipV ? (1.0 - UV[1]) : UV[1];

    float val_center = get_val_safe(TextureFile, final_u, final_v, Channel, InvertColor, Gain);
    
    if (Smoothness <= 0.001) {
       
        outSDF = (SurfaceLevel - val_center) * Amplitude;
    } 
    else {
     
        float signed_val = (val_center - SurfaceLevel) * 2.0;
        outSDF = signed_val * Smoothness * Amplitude * -1.0; 
    }
}