// Copyright 2025 IMAN SHIRANI
// Licensed under the Apache 2.0 License
// https://github.com/ADN-DevTech/3dsMax-OSL-Shaders/blob/master/LICENSE.txt

// SDF Box Shader
// SDF_Box.osl by IMAN SHIRANI
// 2025-09-11



shader SDF_Box
[[
    string logo     = "SDF.png"
]]

(
    point Position = P,
    vector Size = vector(1.0),

    output float SDF_Out = 0.0
)
{
    // 
    vector q = abs(Position) - Size;

    // 
    float outside_dist = length(max(q, 0.0));

    // 
    float inside_dist = min(max(q[0], max(q[1], q[2])), 0.0);

    SDF_Out = outside_dist + inside_dist;
}