// SDF Ellipse Shader
// SDF_Ellipse.osl by IMAN SHIRANI
// 2025-09-11



shader SDF_Ellipse
[[
    string logo     = "SDF.png"
]]
(
    point Position = P,
    
    vector Radii = vector(1.0, 0.5, 1.0),

    output float SDF_Out = 0.0
)
{
    
    vector scaled_p = Position / Radii;
    float dist_in_scaled_space = length(scaled_p) - 1.0;
    float min_radius = min(Radii[0], min(Radii[1], Radii[2]));

    SDF_Out = dist_in_scaled_space * min_radius;
}