// Copyright 2025 IMAN SHIRANI
// Licensed under the Apache 2.0 License
// https://github.com/ADN-DevTech/3dsMax-OSL-Shaders/blob/master/LICENSE.txt


// SDF_Shape_Arc.osl by IMAN SHIRANI
// 2025-11-25

shader SDF_Shape_Arc

[[
        string category = "SDF\\Primitives",
    string logo     = "SDF.png"
]]
(
    point Position = P,
    float Angle_Open = 0.2 [[ string label = "Opening Aperture (0-1)" ]],
    float Radius = 0.5 [[ string label = "Radius" ]],
    float Thickness = 0.05 [[ string label = "Thickness" ]],
    output float SDF_Out = 0.0
)
{
    
    float ta = Angle_Open * 3.141593;
    vector sc = vector(sin(ta), cos(ta), 0.0);
    
    point p = Position;
    
    p[0] = abs(p[0]);
    
    
    float k = (sc[1]*p[0] > sc[0]*p[1]) ? dot(vector(p[0],p[1],0), sc) : length(vector(p[0],p[1],0));
    
    SDF_Out = sqrt(dot(vector(p[0],p[1],0), vector(p[0],p[1],0)) + Radius*Radius - 2.0*Radius*k) - Thickness;
}