// Copyright 2025 IMAN SHIRANI
// Licensed under the Apache 2.0 License
// https://github.com/ADN-DevTech/3dsMax-OSL-Shaders/blob/master/LICENSE.txt

// SDF_Shape_Heart.osl by IMAN SHIRANI
// 2025-11-25
shader SDF_Shape_Heart

[[
        string category = "SDF\\Primitives",
    string logo     = "SDF.png"
]]


(
    point Position = P,
    float Size = 1.0 [[ string label = "Size" ]],
    float CornerRadius = 0.0 [[ string label = "Corner Radius", float min = 0.0 ]],
    output float SDF_Out = 0.0
)
{
   
    point p_raw = Position / Size;
    
    
    p_raw[1] -= 0.5;
    
    
    vector p = vector(abs(p_raw[0]), p_raw[1], 0.0);
    
    float d = 0.0;
    
    
    if (p[1] + p[0] > 1.0) {
       
        vector a = p - vector(0.25, 0.75, 0.0);
        d = sqrt(dot(a,a)) - sqrt(2.0)/4.0;
    } else {
       
        vector b = p - vector(0.0, 1.0, 0.0);
        
        float m = p[0] + p[1];
        vector c = p - 0.5 * max(m, 0.0);
        
        float d1 = dot(b,b);
        float d2 = dot(c,c);
        
        d = sqrt(min(d1, d2));
        
        
        if (p[0] - p[1] < 0.0) d = -d;
    }
    
    
    SDF_Out = (d * Size) - CornerRadius;
}