// Copyright 2025 IMAN SHIRANI
// Licensed under the Apache 2.0 License
// https://github.com/ADN-DevTech/3dsMax-OSL-Shaders/blob/master/LICENSE.txt

// SDF_Shape_Rhombus.osl by IMAN SHIRANI
// 2025-11-25
shader SDF_Shape_Rhombus
[[
        string category = "SDF\\Primitives",
    string logo     = "SDF.png"
]]

(
    point Position = P,
    float Width = 0.5 [[ string label = "Width" ]],
    float Height = 0.8 [[ string label = "Height" ]],
    float CornerRadius = 0.0 [[ string label = "Corner Radius", float min = 0.0 ]],
    output float SDF_Out = 0.0
)
{
    
    point p_raw = abs(Position);
    vector p = vector(p_raw[0], p_raw[1], 0.0);
    vector b = vector(Width, Height, 0.0);
    
    float h = clamp((-2.0*dot(p,b) + dot(b,b)) / dot(b,b), -1.0, 1.0);
    
    
    float d = length(p - 0.5*b*vector(1.0-h, 1.0+h, 0.0));
    
    
    float s = p[0]*b[1] + p[1]*b[0] - b[0]*b[1];
    d = d * sign(s);
    
    SDF_Out = d - CornerRadius;
}