// Copyright 2025 IMAN SHIRANI
// Licensed under the Apache 2.0 License
// https://github.com/ADN-DevTech/3dsMax-OSL-Shaders/blob/master/LICENSE.txt

// SDF_Shape_Pie.osl by IMAN SHIRANI
// 2025-11-25



shader SDF_Shape_Pie

[[
    string logo     = "SDF.png"
]]
(
    point Position = P,
    float Angle = 0.5 [[ string label = "Angle (0 to 1)", float min = 0.0, float max = 1.0 ]],
    float Radius = 0.5 [[ string label = "Radius" ]],
    output float SDF_Out = 0.0
)
{
    
    float a = Angle * 3.141593; 
    
    
    vector c = vector(sin(a), cos(a), 0.0);
    
    
    point p = Position;
    p[0] = abs(p[0]); 
    
    float l = length(vector(p[0], p[1], 0)) - Radius;
    
    
    float m = length(vector(p[0], p[1], 0) - c*clamp(dot(vector(p[0], p[1], 0), c), 0.0, Radius)); 
    
    float d = max(l, m*sign(c[1]*p[0] - c[0]*p[1]));
    
    SDF_Out = d;
}