// Copyright 2025 IMAN SHIRANI
// Licensed under the Apache 2.0 License
// https://github.com/ADN-DevTech/3dsMax-OSL-Shaders/blob/master/LICENSE.txt

// SDF Egg Shader
// SDF_Egg.osl by IMAN SHIRANI
// 2025-09-11



float smin(float a, float b, float k) {
    float h = clamp(0.5 + 0.5 * (b - a) / k, 0.0, 1.0);
    return mix(b, a, h) - k * h * (1.0 - h);
}

shader SDF_Egg
[[
    string logo     = "SDF.png"
]]

(
    point Position = P,

    
    float BottomRadius = 1.0,   
    float TopRadius = 0.7,      
    float Height = 1.5,         
    float Smoothness = 0.5,     

    output float SDF_Out = 0.0
)
{
     
    float sphere1_sdf = distance(Position, point(0, 0, 0)) - BottomRadius;

     
    point top_sphere_center = point(0, Height, 0);
    float sphere2_sdf = distance(Position, top_sphere_center) - TopRadius;

    
    SDF_Out = smin(sphere1_sdf, sphere2_sdf, Smoothness);
}