// SDF_Shape_Trapezoid.osl by IMAN SHIRANI
// 2025-11-25
shader SDF_Shape_Trapezoid
[[
    string logo     = "SDF.png"
]]

(
    point Position = P,
    float TopWidth = 0.3 [[ string label = "Top Width" ]],
    float BottomWidth = 0.5 [[ string label = "Bottom Width" ]],
    float Height = 0.5 [[ string label = "Height" ]],
    float CornerRadius = 0.0 [[ string label = "Corner Radius", float min = 0.0 ]],
    output float SDF_Out = 0.0
)
{
    point p_raw = Position;
    p_raw[0] = abs(p_raw[0]); 
    vector p = vector(p_raw[0], p_raw[1], 0.0);
    
    float r1 = BottomWidth;
    float r2 = TopWidth;
    float he = Height;
    
    vector k1 = vector(r2, he, 0.0);
    vector k2 = vector(r2-r1, 2.0*he, 0.0);
    
    vector pa = p - vector(0.0, -he, 0.0); 
    
    p[1] += he; 
    
    vector pa_iq = vector(p[0]-r1, p[1], 0.0); 
    vector ba = k2;
    
    float h = clamp(dot(pa_iq,ba)/dot(ba,ba), 0.0, 1.0);
    float d = length(pa_iq - ba*h);
    
    
    float s = max((p[0]-r1) + (r1-r2)*p[1]/(2.0*he), p[1] - 2.0*he); 
    
    if (s < 0.0 && p[1] > 0.0) d = -d;
    
    
    
    SDF_Out = d - CornerRadius;
}