// Copyright 2025 IMAN SHIRANI
// Licensed under the Apache 2.0 License
// https://github.com/ADN-DevTech/3dsMax-OSL-Shaders/blob/master/LICENSE.txt

// SDF Box Shader
// SDF_Box.osl by IMAN SHIRANI
// 2025-09-11



shader SDF_Cylinder
[[
    string logo     = "SDF.png"
]]

(
    point Position = P,
    float Height = 2.0,
    float Radius = 0.5,

    output float SDF_Out = 0.0
)
{
    
    
    vector d = abs(vector(length(vector(Position[0], Position[2], 0.0)), Position[1], 0.0)) - vector(Radius, Height / 2.0, 0.0);

    
    float outside_dist = length(max(d, 0.0));
    float inside_dist = min(max(d[0], d[1]), 0.0);
    
    SDF_Out = outside_dist + inside_dist;
}