// Copyright 2025 IMAN SHIRANI
// Licensed under the Apache 2.0 License
// https://github.com/ADN-DevTech/3dsMax-OSL-Shaders/blob/master/LICENSE.txt


// SDF Sphere Shader
// SDF_Sphere.osl by IMAN SHIRANI
// 2025-09-11



shader SDF_Sphere
[[
        string category = "SDF\\Primitives",
    string logo     = "SDF.png"
]]
(
    
    point Position = P,
    float Radius = 1.0,

    
    output float SDF_Out = 0.0
)
{
    
    SDF_Out = distance(Position, point(0, 0, 0)) - Radius;
}