// Copyright 2025 IMAN SHIRANI
// Licensed under the Apache 2.0 License
// https://github.com/ADN-DevTech/3dsMax-OSL-Shaders/blob/master/LICENSE.txt

// SDF_Shape_CoolS.osl by IMAN SHIRANI
// 2025-11-25



shader SDF_Shape_CoolS
[[
        string category = "SDF\\Primitives",
    string logo     = "SDF.png"
]]

(
    point Position = P,
    float Size = 1.0 [[ string label = "Scale" ]],
    float Thickness = 0.08 [[ string label = "Thickness" ]],
    output float SDF_Out = 0.0
)
{
    point p = Position / Size;
    float th = Thickness;
    
    
    float sdBox(vector p, vector b) {
        vector d = abs(p) - b;
        return length(max(d, 0.0)) + min(max(d[0], d[1]), 0.0);
    }
    
   
    float l1 = sdBox(vector(p[0]+0.4, p[1]-0.25, 0), vector(th, 0.5, 0));
    
    float l3 = sdBox(vector(p[0]-0.4, p[1]+0.25, 0), vector(th, 0.5, 0));
    
    float l2a = sdBox(vector(p[0], p[1]-0.25, 0), vector(th, 0.5, 0));
    float l2b = sdBox(vector(p[0], p[1]+0.25, 0), vector(th, 0.5, 0));
    
    
    vector p_top = vector(p[0], p[1]-0.85, 0);
    p_top[0] = abs(p_top[0]);
    
    vector pa = p_top - vector(0.0, 0.4, 0);
    vector ba = vector(0.4, -0.4, 0);
    float h = clamp(dot(pa,ba)/dot(ba,ba), 0.0, 1.0);
    float top_chev = length(pa - ba*h) - th;
    
    
    vector p_bot = vector(p[0], p[1]+0.85, 0); 
    p_bot[0] = abs(p_bot[0]);
    vector pa2 = p_bot - vector(0.0, -0.4, 0);
    vector ba2 = vector(0.4, 0.4, 0);
    float h2 = clamp(dot(pa2,ba2)/dot(ba2,ba2), 0.0, 1.0);
    float bot_chev = length(pa2 - ba2*h2) - th;

    
    float d = min(min(l1, l3), min(l2a, l2b));
    d = min(d, min(top_chev, bot_chev));
    
    
    SDF_Out = d * Size;
}