// Copyright 2025 IMAN SHIRANI
// Licensed under the Apache 2.0 License
// https://github.com/ADN-DevTech/3dsMax-OSL-Shaders/blob/master/LICENSE.txt

// SDF_Shape_Triangle_Equilateral.osl by IMAN SHIRANI
// 2025-11-25
shader SDF_Shape_Triangle_Equilateral
[[
        string category = "SDF\\Primitives",
    string logo     = "SDF.png"
]]

(
    point Position = P,
    float Radius = 0.5 [[ string label = "Size" ]],
    float CornerRadius = 0.0 [[ string label = "Corner Radius", float min = 0.0 ]],
    output float SDF_Out = 0.0
)
{
    point p_raw = Position;
    p_raw[0] = abs(p_raw[0]);
    vector p = vector(p_raw[0], p_raw[1], 0.0);
    float r = Radius;
    
    float k = 1.73205080757; 
    
    if (p[0] + k*p[1] > 0.0) {
        vector temp = vector((p[0]-k*p[1])/2.0, (-k*p[0]-p[1])/2.0, 0.0);
        p = temp;
    }
    
    p[0] -= clamp(p[0], -2.0*r, 0.0);
    float d = -length(p) * sign(p[1]);
    
    SDF_Out = d - CornerRadius;
}