// Copyright 2025 IMAN SHIRANI
// Licensed under the Apache 2.0 License
// https://github.com/ADN-DevTech/3dsMax-OSL-Shaders/blob/master/LICENSE.txt

// SDF_Capsule.osl by IMAN SHIRANI
// 2025-11-25

shader SDF_Capsule

[[
        string category = "SDF\\Primitives",
    string logo     = "SDF.png"
]]

(
    point Position = P,
    
    point Point_A = point(0, 0, 0) [[ string label = "Start Point" ]],
    point Point_B = point(0, 2, 0) [[ string label = "End Point" ]],
    float Radius = 0.5 [[ string label = "Radius", float min = 0.0 ]],
    
    output float SDF_Out = 0.0
)
{
    // فرمول ریاضی کپسول (فاصله تا یک خط)
    vector pa = Position - Point_A;
    vector ba = Point_B - Point_A;
    
    float h = clamp(dot(pa, ba) / dot(ba, ba), 0.0, 1.0);
    
    SDF_Out = length(pa - ba * h) - Radius;
}