// Copyright 2025 IMAN SHIRANI
// Licensed under the Apache 2.0 License
// https://github.com/ADN-DevTech/3dsMax-OSL-Shaders/blob/master/LICENSE.txt

// SDF Torus Shader
// SDF_Torus.osl by IMAN SHIRANI
// 2025-09-11



shader SDF_Torus
[[
        string category = "SDF\\Primitives",
    string logo     = "SDF.png"
]]
(
    point Position = P,
    float MajorRadius = 1.0,
    float MinorRadius = 0.2,

    output float SDF_Out = 0.0
)
{
    
    vector q = vector(length(vector(Position[0], Position[2], 0.0)) - MajorRadius, Position[1], 0.0);

    
    SDF_Out = length(q) - MinorRadius;
}