// Copyright 2025 IMAN SHIRANI
// Licensed under the Apache 2.0 License
// https://github.com/ADN-DevTech/3dsMax-OSL-Shaders/blob/master/LICENSE.txt

// SDF_Preview_3D.osl by IMAN SHIRANI
// 2025-11-25


shader SDF_Preview_3D
[[
    string logo     = "SDF.png"
]]
(
    float InputSDF = 0.0,
    
    color BaseColor = color(0.2, 0.4, 0.8) [[ string label = "Color" ]],
    vector LightDir = vector(-0.5, 0.5, 1.0) [[ string label = "Light Direction" ]],
    float Smoothness = 0.001 [[ string label = "Normal Smoothness" ]],
    
   
    float dx = 0.0 [[ string widget = "null", int lockgeom = 0 ]], 
    float dy = 0.0 [[ string widget = "null", int lockgeom = 0 ]],
    
    output color OutColor = color(0.0),
    output vector OutNormal = vector(0.0)
)
{
    
    if (InputSDF < 0.0) {
        
        
        vector n = normalize(vector(Dx(InputSDF), Dy(InputSDF), Smoothness));
        
        
        vector l = normalize(LightDir);
        float diffuse = max(dot(n, l), 0.0);
        
        
        float ambient = 0.2;
        
        
        float rim = 1.0 - max(dot(n, vector(0,0,1)), 0.0);
        rim = pow(rim, 3.0) * 0.5;
        
        OutColor = BaseColor * (diffuse + ambient) + rim;
        OutNormal = n; 
    } 
    else {
        
        OutColor = color(0.0, 0.0, 0.0); 
        OutNormal = vector(0, 0, 1); 
    }
}