// Copyright 2025 IMAN SHIRANI
// Licensed under the Apache 2.0 License
// https://github.com/ADN-DevTech/3dsMax-OSL-Shaders/blob/master/LICENSE.txt

// SDF_to_Normal.osl by IMAN SHIRANI
// 2025-11-25


shader SDF_to_Normal
[[
    string logo     = "SDF.png"
]]
(
    float InputSDF = 0.0,
    
    
    float Smoothness = 0.001 [[ string label = "Precision / Delta" ]],
    
    
    int AsColor = 1 [[ string label = "Output as Normal Map Color", string widget = "checkbox" ]],
    
    output vector OutNormal = vector(0.0),
    output color OutColor = color(0.5, 0.5, 1.0)
)
{
    
    
    vector n = vector(0.0);
    
    
    n = normalize(vector(Dx(InputSDF), Dy(InputSDF), Smoothness));
    
    
    OutNormal = n;
    
    
    if (AsColor) {
        OutColor = color(n[0] * 0.5 + 0.5, n[1] * 0.5 + 0.5, n[2] * 0.5 + 0.5);
    } else {
        OutColor = color(n);
    }
}