// Copyright 2025 IMAN SHIRANI
// Licensed under the Apache 2.0 License
// https://github.com/ADN-DevTech/3dsMax-OSL-Shaders/blob/master/LICENSE.txt

// SDF_Smooth_Difference.osl by IMAN SHIRANI
// 2025-11-25



shader SDF_Smooth_Difference
[[
        string category = "SDF\\Operators",
    string logo     = "SDF.png"
]]
(
    float SDF_Base = 0.0 [[ string label = "Shape A (Base)" ]],
    float SDF_Cutter = 0.0 [[ string label = "Shape B (Cutter)" ]],
    
    float Smoothness = 0.1 [[ string label = "Smooth Factor", float min = 0.001 ]],
    
    output float SDF_Out = 0.0
)
{
    
    float k = max(Smoothness, 0.0001);
    
    
    float h = clamp(0.5 - 0.5 * (SDF_Base + SDF_Cutter) / k, 0.0, 1.0);
    
    
    SDF_Out = mix(SDF_Base, -SDF_Cutter, h) + k * h * (1.0 - h);
}