// Copyright 2025 IMAN SHIRANI
// Licensed under the Apache 2.0 License
// https://github.com/ADN-DevTech/3dsMax-OSL-Shaders/blob/master/LICENSE.txt


// SDF_Boolean.osl by IMAN SHIRANI
// 2025-09-11


shader SDF_Boolean
[[
        string category = "SDF\\Operators",
    string logo     = "SDF.png"
]]

(
    float SDF_A = 0.0,
    float SDF_B = 0.0,
    
    
    int operation = 0
    [[
        string widget = "mapper",
        string options = "Union:0|Subtract:1|Intersect:2"
    ]],

    output float SDF_Out = 0.0
)
{
    if (operation == 0) // Union
    {
        SDF_Out = min(SDF_A, SDF_B);
    }
    else if (operation == 1) // Subtract
    {
        SDF_Out = max(SDF_A, -SDF_B);
    }
    else // Intersect
    {
        SDF_Out = max(SDF_A, SDF_B);
    }
}